app = "brain-bloom-worker"
primary_region = "iad"

[build]
builder = "paketobuildpacks/builder:base"
[build.args]

BP_BUILD_COMMAND = "/workspace/build.sh"
[env]
  PYTHONUNBUFFERED = "1"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  worker = "python manage.py runworker default"

  [mounts]
  source = "brain_bloom_media"
  destination = "/code/media"