# fly.toml app configuration file generated for brain-bloom-django on 2025-04-07T22:59:51+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brain-bloom-django'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[processes]
  app = 'daphne -b 0.0.0.0 -p 8000 myproject.asgi'
  celery = 'celery -A myproject/settings.py worker --loglevel=INFO'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
