services:
  - type: worker
    name: brain-bloom-celery-worker
    env: python
    buildCommand: "pip install -r requirements.txt --index-url https://download.pytorch.org/whl/cpu"
    startCommand: "celery -A myproject worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: brain-bloom
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: brain-bloom-redis
          property: connectionString
  - type: worker
    name: brain-bloom-celery-beat
    env: python
    buildCommand: "pip install -r requirements.txt --index-url https://download.pytorch.org/whl/cpu"
    startCommand: "celery -A myproject beat --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: brain-bloom
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: brain-bloom-redis
          property: connectionString