# Generated by Django 3.2.25 on 2025-03-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_department_user_profile_picture_user_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('title', 'date', 'time', 'creator')},
        ),
    ]
