# Generated by Django 3.2.25 on 2025-03-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250314_1624'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('title', 'date', 'time', 'creator')},
        ),
    ]
