# Generated by Django 3.2.25 on 2025-03-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='key_points',
            field=models.JSONField(default=list),
        ),
    ]
