# Generated by Django 3.2.25 on 2025-03-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_summary_key_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='key_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.CheckConstraint(check=models.Q(('key_points__isnull', True), ('key_points__regex', '^\\[.*\\]$'), _connector='OR'), name='valid_json_key_points'),
        ),
    ]
