# Generated by Django 3.2.25 on 2025-03-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_quiz_quizresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='actual_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
