# Generated by Django 3.2.25 on 2025-03-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_summary_actual_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to='accounts.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.quiz'),
        ),
        migrations.AlterUniqueTogether(
            name='quizresponse',
            unique_together={('room', 'user', 'quiz')},
        ),
    ]
