# Generated by Django 3.2.25 on 2025-03-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_studypartnerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
