# Generated by Django 5.1.7 on 2025-04-02 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_room_topic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studypartnerrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studypartnerrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='studypartnerrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='accounts.user'),
        ),
    ]
